[package]
name = "pay-respects"
version = "0.4.17"
edition = "2021"

# for crates.io
description = "Terminal command correction, alternative to thefuck written in Rust"
repository = "https://github.com/iffse/pay-respects"
keywords = ["cli", "terminal", "utility", "shell"]
categories = ["command-line-utilities"]
license = "AGPL-3.0"
include = [
	"**/*.rs",
	"**/*.toml",
]

[dependencies]
colored = "2.0"
sys-locale = "0.3.2"
rust-i18n = "3"
regex-lite = "0.1"

pay-respects-parser = "0.2.2"

[profile.release]
strip = true
codegen-units = 1
lto = true
