[workspace]
resolver = "2"
members = [
	"pay-respects",
	"pay-respects-parser",
	# optional modules
	# "pay-respects-module-runtime-rules",
	# "pay-respects-module-request-ai"
]

[profile.release]
strip = true
codegen-units = 1
lto = true

