[workspace]
resolver = "2"
members = [
	"core",
	"parser",
	"utils",
	# optional modules
	"module-runtime-rules",
	"module-request-ai",
	]

[profile.release]
strip = true
codegen-units = 1
lto = true

