command = "cat"

[[match_err]]
pattern = [
	"no such file or directory"
]
suggest = [
'''
cat {{typo[1](file)}} '''
]

[[match_err]]
pattern = [
	"is a directory"
]
suggest = [
'''
ls {{command[1:]}}'''
]
