[package]
name = "pay-respects"
authors = ["iff <iff@ik.me>"]
version = "0.5.15"
edition = "2021"

# for crates.io
description = "Terminal command suggestion, alternative to thefuck written in Rust with AI support"
homepage = "https://codeberg.org/iff/pay-respects"
repository = "https://github.com/iffse/pay-respects"
keywords = ["cli", "terminal", "utility", "shell"]
categories = ["command-line-utilities"]
license = "AGPL-3.0"
include = ["**/*.rs", "**/*.toml"]

[dependencies]
colored = "2"
sys-locale = "0.3"
rust-i18n = "3"
regex-lite = "0.1"

inquire = "0.7.5"

pay-respects-parser = { version = "0.3.2", path = "../parser" }
pay-respects-utils = {version = "0.1.0", path = "../utils"}
