command = "_PR_general"

[[match_err]]
pattern = [
	"command not found",
	"unknown command",
	"nu::shell::external_command",
	"is not recognized as a name of a cmdlet"
]
suggest = [
'''
{{exes[0]}} {{command[1:]}} '''
]
