command = "yarn"

[[match_err]]
pattern = [
	"not found"
]
suggest = [
'''
#[err_contains(command)]
{{command[0]}} {{typo[1](
access,
add,
audit,
autoclean,
bin,
cache,
check,
config,
create,
exec,
generate-lock-entry,
generateLockEntry,
global,
help,
import,
info,
init,
install,
licenses,
link,
list,
login,
logout,
node,
outdated,
owner,
pack,
policies,
publish,
remove,
run,
tag,
team,
unlink,
unplug,
upgrade,
upgrade-interactive,
upgradeInteractive,
version,
versions,
why,
workspace,
workspaces
)}} {{command[2:]}} '''
]

[[match_err]]
pattern = [
	"error `install` has been replaced with `add` to add new dependencies."
]
suggest = [
'''
yarn add {{command[2:]}} '''
]
